spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain
    min-response-size: 1024

app:
  frontend:
    url: https://jobsy-app.vercel.app

logging:
  level:
    root: INFO
  file:
    name: logs/jobsy.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
